#!/bin/sh
set -e

bootstrap() {
  if ! command -v $2 >/dev/null; then
    echo "Installing $1 ..."
    $3
  else
    echo "$1 already installed. Skipping."
  fi
}

init() {
  bootstrap "Xcode" "cc" "xcode-select --install"
  bootstrap "Homebrew" "brew" "/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
  bootstrap "Ansible" "ansible" "brew install ansible"
}

case "$1" in
  "-init")
    init
    ;;
  *)
    ansible-playbook provisioning.yml -i inventory $@
    ;;
esac