---
- hosts: all
  become: false
  gather_facts: false
  vars:
    brew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/versions

    brew_casks:
      - skype
      - sublime-text-dev

    brew_packages:
      - ansible
      - duti
      - elixir
      - emacs
      - erlang
      - ffmpeg
      - fish
      - fzf
      - git
      - imagemagick
      - libmagic
      - mc
      - node
      - openssl
      - optipng
      - postgresql
      - python
      - redis
      - rsync
      - ruby-install
      - vim
      - wget

  tasks:
    - name: Install required Homebrew Taps
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ brew_taps }}"

    - name: Install packages with Homebrew
      homebrew: name={{ item }} state=present
      with_items: "{{ brew_packages }}"

    - name: Install applications with Homebrew Cask
      shell: brew cask install {{ item }}
      with_items: "{{ brew_casks }}"
